# Advanced Retrieval with LangChain

In the following notebook, we'll explore various methods of advanced retrieval using LangChain!

We'll touch on:

- Naive Retrieval
- Best-Matching 25 (BM25)
- Multi-Query Retrieval
- Parent-Document Retrieval
- Contextual Compression (a.k.a. Rerank)
- Ensemble Retrieval
- Semantic chunking

We'll also discuss how these methods impact performance on our set of documents with a simple RAG chain.

There will be two breakout rooms:

- 🤝 Breakout Room Part #1
  - Task 1: Getting Dependencies!
  - Task 2: Data Collection and Preparation
  - Task 3: Setting Up QDrant!
  - Task 4-10: Retrieval Strategies
- 🤝 Breakout Room Part #2
  - Activity: Evaluate with Ragas

# 🤝 Breakout Room Part #1

## Task 1: Getting Dependencies!

We're going to need a few specific LangChain community packages, like OpenAI (for our [LLM](https://platform.openai.com/docs/models) and [Embedding Model](https://platform.openai.com/docs/guides/embeddings)) and Cohere (for our [Reranker](https://cohere.com/rerank)).

We'll also provide our OpenAI key, as well as our Cohere API key.

In [49]:
import os
import getpass

os.environ["OPENAI_API_KEY"] = getpass.getpass("Enter your OpenAI API Key:")

In [50]:
os.environ["COHERE_API_KEY"] = getpass.getpass("Cohere API Key:")

In [51]:
print("🔧 Setting up ALL dependencies for Breakout Room Part #2...")

# 1. LangSmith Setup (FIRST - before any other operations)
os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_API_KEY"] = getpass.getpass("Enter your LangSmith API Key:")
from uuid import uuid4
os.environ["LANGCHAIN_PROJECT"] = f"Advanced_Retrieval_Evaluation_{uuid4().hex[0:8]}"

# 2. NLTK Setup (required for Ragas)
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

# 3. Ragas Imports
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from ragas.testset import TestsetGenerator
from ragas import evaluate, EvaluationDataset
from ragas.metrics import (
    LLMContextRecall, 
    Faithfulness, 
    FactualCorrectness, 
    ResponseRelevancy, 
    ContextEntityRecall, 
    NoiseSensitivity,
    ContextPrecision
    )
from ragas import RunConfig

# 4. LangSmith Client
from langsmith import Client
client = Client()

# 5. Test LangSmith connection
from langchain_openai import ChatOpenAI
test_llm = ChatOpenAI(model="gpt-4.1-nano")
test_response = test_llm.invoke("Test message for LangSmith tracing")

print("✅ ALL dependencies loaded successfully!")
print("✅ LangSmith environment configured!")
print("✅ NLTK packages downloaded!")
print("✅ Ragas components imported!")
print("✅ LangSmith tracing working!")

🔧 Setting up ALL dependencies for Breakout Room Part #2...


[nltk_data] Downloading package punkt to
[nltk_data]     /Users/ashapondicherry/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /Users/ashapondicherry/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


✅ ALL dependencies loaded successfully!
✅ LangSmith environment configured!
✅ NLTK packages downloaded!
✅ Ragas components imported!
✅ LangSmith tracing working!


## Task 2: Data Collection and Preparation

We'll be using our Loan Data once again - this time the strutured data available through the CSV!

### Data Preparation

We want to make sure all our documents have the relevant metadata for the various retrieval strategies we're going to be applying today.

In [52]:
from langchain_community.document_loaders.csv_loader import CSVLoader
from datetime import datetime, timedelta

loader = CSVLoader(
    file_path=f"./data/complaints.csv",
    metadata_columns=[
      "Date received", 
      "Product", 
      "Sub-product", 
      "Issue", 
      "Sub-issue", 
      "Consumer complaint narrative", 
      "Company public response", 
      "Company", 
      "State", 
      "ZIP code", 
      "Tags", 
      "Consumer consent provided?", 
      "Submitted via", 
      "Date sent to company", 
      "Company response to consumer", 
      "Timely response?", 
      "Consumer disputed?", 
      "Complaint ID"
    ]
)

loan_complaint_data = loader.load()

for doc in loan_complaint_data:
    doc.page_content = doc.metadata["Consumer complaint narrative"]

Let's look at an example document to see if everything worked as expected!

In [53]:
loan_complaint_data[0]

Document(metadata={'source': './data/complaints.csv', 'row': 0, 'Date received': '03/27/25', 'Product': 'Student loan', 'Sub-product': 'Federal student loan servicing', 'Issue': 'Dealing with your lender or servicer', 'Sub-issue': 'Trouble with how payments are being handled', 'Consumer complaint narrative': "The federal student loan COVID-19 forbearance program ended in XX/XX/XXXX. However, payments were not re-amortized on my federal student loans currently serviced by Nelnet until very recently. The new payment amount that is effective starting with the XX/XX/XXXX payment will nearly double my payment from {$180.00} per month to {$360.00} per month. I'm fortunate that my current financial position allows me to be able to handle the increased payment amount, but I am sure there are likely many borrowers who are not in the same position. The re-amortization should have occurred once the forbearance ended to reduce the impact to borrowers.", 'Company public response': 'None', 'Company'

## Task 3: Setting up QDrant!

Now that we have our documents, let's create a QDrant VectorStore with the collection name "LoanComplaints".

We'll leverage OpenAI's [`text-embedding-3-small`](https://openai.com/blog/new-embedding-models-and-api-updates) because it's a very powerful (and low-cost) embedding model.

> NOTE: We'll be creating additional vectorstores where necessary, but this pattern is still extremely useful.

In [54]:
from langchain_community.vectorstores import Qdrant
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")

vectorstore = Qdrant.from_documents(
    loan_complaint_data,
    embeddings,
    location=":memory:",
    collection_name="LoanComplaints"
)

## Task 4: Naive RAG Chain

Since we're focusing on the "R" in RAG today - we'll create our Retriever first.

### R - Retrieval

This naive retriever will simply look at each review as a document, and use cosine-similarity to fetch the 10 most relevant documents.

> NOTE: We're choosing `10` as our `k` here to provide enough documents for our reranking process later

In [55]:
naive_retriever = vectorstore.as_retriever(search_kwargs={"k" : 10})

### A - Augmented

We're going to go with a standard prompt for our simple RAG chain today! Nothing fancy here, we want this to mostly be about the Retrieval process.

In [56]:
from langchain_core.prompts import ChatPromptTemplate

RAG_TEMPLATE = """\
You are a helpful and kind assistant. Use the context provided below to answer the question.

If you do not know the answer, or are unsure, say you don't know.

Query:
{question}

Context:
{context}
"""

rag_prompt = ChatPromptTemplate.from_template(RAG_TEMPLATE)

### G - Generation

We're going to leverage `gpt-4.1-nano` as our LLM today, as - again - we want this to largely be about the Retrieval process.

In [57]:
from langchain_openai import ChatOpenAI

chat_model = ChatOpenAI(model="gpt-4.1-nano")

### LCEL RAG Chain

We're going to use LCEL to construct our chain.

> NOTE: This chain will be exactly the same across the various examples with the exception of our Retriever!

In [58]:
from langchain_core.runnables import RunnablePassthrough
from operator import itemgetter
from langchain_core.output_parsers import StrOutputParser

naive_retrieval_chain = (
    # INVOKE CHAIN WITH: {"question" : "<<SOME USER QUESTION>>"}
    # "question" : populated by getting the value of the "question" key
    # "context"  : populated by getting the value of the "question" key and chaining it into the base_retriever
    {"context": itemgetter("question") | naive_retriever, "question": itemgetter("question")}
    # "context"  : is assigned to a RunnablePassthrough object (will not be called or considered in the next step)
    #              by getting the value of the "context" key from the previous step
    | RunnablePassthrough.assign(context=itemgetter("context"))
    # "response" : the "context" and "question" values are used to format our prompt object and then piped
    #              into the LLM and stored in a key called "response"
    # "context"  : populated by getting the value of the "context" key from the previous step
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's see how this simple chain does on a few different prompts.

> NOTE: You might think that we've cherry picked prompts that showcase the individual skill of each of the retrieval strategies - you'd be correct!

In [59]:
naive_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'The most common issues with loans, based on the complaints provided, appear to involve mismanagement and poor handling by loan servicers. Specific recurring problems include errors in loan balances and interest calculations, difficulty applying payments correctly, mishandling loan transfers without proper notification, incorrect reporting of account status to credit bureaus, and allegations of unfair or predatory practices such as steering borrowers into unfavorable repayment plans or withholding accurate information. \n\nIn summary, a prevalent issue is **mismanagement or mishandling of student loans by servicers**, leading to errors, confusion, and financial hardship for borrowers.'

In [60]:
naive_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided information, several complaints were explicitly noted as not handled in a timely manner. For example:\n\n- Complaint ID 12709087 (MOHELA) received on 03/28/25 was marked as "Timely response?": No, indicating it was not handled promptly.\n- Complaint ID 12973003 (EdFinancial Services) received on 04/14/25 was marked as "Timely response?": Yes, so this one was handled in time.\n- Complaint ID 12975634 (Maximus Federal Services, Inc.) received on 04/14/25 was marked as "Timely response?": Yes.\n- Complaint ID 12832400 (Maximus Federal Services, Inc.) received on 04/05/25 was marked as "Timely response?": Yes.\n- Other complaints also have notes on delays, but the one explicitly identified as not handled in a timely manner is the complaint to MOHELA.\n\nTherefore, yes, some complaints did not get handled in a timely manner.'

In [61]:
naive_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

'People failed to pay back their loans for various reasons, including:\n\n1. Lack of clear communication and notification about loan status and payment resumption, leading to unintentional delinquencies.\n2. Difficulty understanding or keeping track of complex interest calculations, fees, and the true amount owed.\n3. Financial hardships such as stagnant wages, inflation, or personal financial crises making it impossible to afford payments without compromising basic necessities.\n4. Limited or no access to flexible repayment options like income-driven repayment plans or the inability to get those plans approved.\n5. Problems with loan servicers moving or mismanaging loans, resulting in missed payments or confusion about payment obligations.\n6. Mismanagement or confusion stemming from transfers between loan holders, lack of notification, and inconsistent or incorrect account information.\n7. High interest rates accumulating over time, causing the debt to grow despite regular payments.\

Overall, this is not bad! Let's see if we can make it better!

## Task 5: Best-Matching 25 (BM25) Retriever

Taking a step back in time - [BM25](https://www.nowpublishers.com/article/Details/INR-019) is based on [Bag-Of-Words](https://en.wikipedia.org/wiki/Bag-of-words_model) which is a sparse representation of text.

In essence, it's a way to compare how similar two pieces of text are based on the words they both contain.

This retriever is very straightforward to set-up! Let's see it happen down below!


In [62]:
from langchain_community.retrievers import BM25Retriever

bm25_retriever = BM25Retriever.from_documents(loan_complaint_data, )

We'll construct the same chain - only changing the retriever.

In [63]:
bm25_retrieval_chain = (
    {"context": itemgetter("question") | bm25_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's look at the responses!

In [64]:
bm25_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'Based on the provided context, the most common issue with loans appears to be dealing with or misunderstandings related to the lender or servicer. Specifically, many complaints involve issues such as incorrect or bad information about the loan, difficulties in making payments (such as applying funds to the principal), disputes over fees or charges, and problems with how the loan is being managed or reported. These types of issues highlight challenges consumers face in communicating with their loan servicers and obtaining accurate or transparent information.'

In [65]:
bm25_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided information, all the complaints in the context received timely responses from the companies. For each complaint, the responses are marked as "Yes" under the "Timely response?" field, indicating that they were handled in a timely manner. Therefore, there is no evidence from this data to suggest that any complaints did not get handled in a timely manner.'

In [66]:
bm25_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

"People failed to pay back their loans for various reasons, including issues with their payment plans, miscommunication or lack of communication from loan servicers, and administrative errors. Specific problems in the provided complaints include:\n\n- Being steered into wrong types of forbearances or having their forbearance requests ignored.\n- Automatic payments being unenrolled or not processed correctly, often without proper notification, leading to missed payments or negative credit reporting.\n- Loan transfers to new servicers like Aidvantage happening without the borrower's awareness, causing confusion and lack of timely information about payments or outstanding balances.\n- Lack of response or assistance from loan servicers when borrowers seek help or request deferments due to financial hardship.\n- Borrowers receiving bills or negative credit reports despite following the proper procedures and making regular payments.\n\nThese issues suggest that administrative errors, poor co

It's not clear that this is better or worse, if only we had a way to test this (SPOILERS: We do, the second half of the notebook will cover this)

#### ❓ Question #1:

Give an example query where BM25 is better than embeddings and justify your answer.

#### Answer:

Example query: "Whats the loan payment terms?"

**Why BM25 would be better here:** BM25 is essentially a fancy word-matching system. It looks for documents that contain the exact words you're searching for. So when you aks about loan payment terms, BM25 will find documets that actually contain those specific words.

**The problem with embeddings:** Embeddings are great at understanding meaning, but sometimes they can be too smart. They might return documents about "repayment schedules" or "monthly installments" because they understand these are related concepts. But if you specifically want documents that mention "payment terms," you might miss relevant documents that use that exact phrase.

**BM25** shines when you need exact word matching rather than semantic understanding.

## Task 6: Contextual Compression (Using Reranking)

Contextual Compression is a fairly straightforward idea: We want to "compress" our retrieved context into just the most useful bits.

There are a few ways we can achieve this - but we're going to look at a specific example called reranking.

The basic idea here is this:

- We retrieve lots of documents that are very likely related to our query vector
- We "compress" those documents into a smaller set of *more* related documents using a reranking algorithm.

We'll be leveraging Cohere's Rerank model for our reranker today!

All we need to do is the following:

- Create a basic retriever
- Create a compressor (reranker, in this case)

That's it!

Let's see it in the code below!

In [67]:
from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_cohere import CohereRerank

compressor = CohereRerank(model="rerank-v3.5")
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=naive_retriever
)

Let's create our chain again, and see how this does!

In [68]:
contextual_compression_retrieval_chain = (
    {"context": itemgetter("question") | compression_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

In [69]:
contextual_compression_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'Based on the provided context, the most common issue with loans appears to be problems related to miscommunication, inaccurate or incomplete information, and mishandling by lenders or servicers. Specifically, there are frequent complaints about errors in loan balances, misapplied payments, wrongful denials of payment plans, and improper handling of personal and loan data. These issues often result in disputes, confusion over balances, and potential violations of privacy laws.'

In [70]:
contextual_compression_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided information, yes, there are complaints that did not get handled in a timely manner. Specifically, the complaint from the individual regarding their student loans, submitted over a year ago, has been open since XXXX and still has not been resolved, with the individual stating it has been nearly 18 months with no resolution. They also mentioned issues with responses taking months and delays in getting contact or resolution.'

In [71]:
contextual_compression_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

'People failed to pay back their loans primarily due to a combination of lack of clear information, miscommunication, and the accumulation of interest over time. Many borrowers were not adequately informed about their repayment obligations or how interest would accrue, especially when loans were transferred between servicers without proper notification. As a result, some believed they were not required to pay or were unaware of ongoing interest that continued to grow, making repayment difficult. Additionally, options like forbearance or deferment led to interest accumulating, which increased the total amount owed and extended the repayment period. Financial hardships, stagnant wages, and lack of qualifying forgiveness programs further contributed to their inability to repay the loans.'

We'll need to rely on something like Ragas to help us get a better sense of how this is performing overall - but it "feels" better!

## Task 7: Multi-Query Retriever

Typically in RAG we have a single query - the one provided by the user.

What if we had....more than one query!

In essence, a Multi-Query Retriever works by:

1. Taking the original user query and creating `n` number of new user queries using an LLM.
2. Retrieving documents for each query.
3. Using all unique retrieved documents as context

So, how is it to set-up? Not bad! Let's see it down below!



In [72]:
from langchain.retrievers.multi_query import MultiQueryRetriever

multi_query_retriever = MultiQueryRetriever.from_llm(
    retriever=naive_retriever, llm=chat_model
)

In [73]:
multi_query_retrieval_chain = (
    {"context": itemgetter("question") | multi_query_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

In [74]:
multi_query_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'The most common issue with loans, based on the provided complaints, appears to be problems related to the handling and management of student loans, including:\n\n- Trouble with how payments are being handled, such as inability to apply extra funds to principal or pay off loans quickly.\n- Errors in loan balances and reported balances, often with disputes over accuracy.\n- Problems with loan servicing decisions, such as being steered into forbearance with accruing interest.\n- Mishandled loan transfers and improper reporting to credit bureaus, including delinquency and default misreporting.\n- Lack of proper documentation, including absence of signed promissory notes.\n- Lack of communication and inadequate customer service from servicers.\n- Unjustified increases in interest rates and fees without proper disclosure.\n- Violations of borrower rights, such as improper or illegal collection practices and failure to provide necessary legal documents.\n\nIn summary, issues related to misma

In [75]:
multi_query_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided complaints, yes, there are complaints indicating that some complaints did not get handled in a timely manner. Specifically:\n\n- Several complaints show responses marked as "No" for timely response, such as complaints received by companies like MOHELA and Maximus Federal Services, which were marked as "No" in response to whether the company responded in a timely manner.\n- Additionally, multiple complaints involve delays or lack of responses over extended periods (e.g., over 1 year, nearly 18 months) where the consumers report no resolution or communication from the companies despite repeated follow-ups.\n\nTherefore, it can be concluded that some complaints were not handled promptly.'

In [76]:
multi_query_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

'People often fail to pay back their loans due to a variety of systemic issues and servicing misconduct, including:\n\n1. Lack of clear or adequate communication from lenders or servicers about repayment obligations, leading borrowers to be unaware of when payments are due or how to manage them.\n2. Being placed into long-term forbearances without being informed that interest would accrue or that such delays could increase the total amount owed.\n3. Mismanagement and wrongful reporting of delinquency, which can negatively impact credit scores unexpectedly.\n4. Failure to offer or inform borrowers about manageable repayment options such as income-driven repayment plans, loan rehabilitation, or forgiveness programs.\n5. Aggressive or coercive practices, such as steering borrowers into difficult consolidation or forbearance practices without full disclosure of consequences.\n6. Systemic failures in record-keeping and data handling, leading to confusion and unintentional default.\n7. Perso

#### ❓ Question #2:

Explain how generating multiple reformulations of a user query can improve recall.

#### Amswer:

The Problem:
When you ask a question, there are often many different ways to phrase the same thing. If you only search with your original question, you might miss relevant documents that use different words or phrases to describe the same concept.

How Multi-Query Retrieval Solves This:
Example: Let's say you ask: "Why did people fail to pay back their loans?"

The system might generate these reformulations:
- "What caused borrowers to default on their loans?"
- "What reasons led to loan repayment failures?"
- "Why couldn't people repay their student loans?"
- "What factors contributed to loan defaults?"
- "Why did borrowers struggle with loan payments?"

Why This Improves Recall:
    1. Different Vocabulary: Each reformulation uses different words. "Default" vs "fail to pay back" vs "struggle with payments" - these might match different documents.
    2. Broader Coverage: Instead of one search, you're now doing 5 searches. You're casting a wider net and catching more relevant documents.
    3. Semantic Variations: The LLM understands that "borrowers" and "people" mean the same thing, or that "default" and "fail to pay back" are related concepts.

## Task 8: Parent Document Retriever

A "small-to-big" strategy - the Parent Document Retriever works based on a simple strategy:

1. Each un-split "document" will be designated as a "parent document" (You could use larger chunks of document as well, but our data format allows us to consider the overall document as the parent chunk)
2. Store those "parent documents" in a memory store (not a VectorStore)
3. We will chunk each of those documents into smaller documents, and associate them with their respective parents, and store those in a VectorStore. We'll call those "child chunks".
4. When we query our Retriever, we will do a similarity search comparing our query vector to the "child chunks".
5. Instead of returning the "child chunks", we'll return their associated "parent chunks".

Okay, maybe that was a few steps - but the basic idea is this:

- Search for small documents
- Return big documents

The intuition is that we're likely to find the most relevant information by limiting the amount of semantic information that is encoded in each embedding vector - but we're likely to miss relevant surrounding context if we only use that information.

Let's start by creating our "parent documents" and defining a `RecursiveCharacterTextSplitter`.

In [77]:
from langchain.retrievers import ParentDocumentRetriever
from langchain.storage import InMemoryStore
from langchain_text_splitters import RecursiveCharacterTextSplitter
from qdrant_client import QdrantClient, models

parent_docs = loan_complaint_data
child_splitter = RecursiveCharacterTextSplitter(chunk_size=750)

We'll need to set up a new QDrant vectorstore - and we'll use another useful pattern to do so!

> NOTE: We are manually defining our embedding dimension, you'll need to change this if you're using a different embedding model.

In [78]:
from langchain_qdrant import QdrantVectorStore

client = QdrantClient(location=":memory:")

client.create_collection(
    collection_name="full_documents",
    vectors_config=models.VectorParams(size=1536, distance=models.Distance.COSINE)
)

parent_document_vectorstore = QdrantVectorStore(
    collection_name="full_documents", embedding=OpenAIEmbeddings(model="text-embedding-3-small"), client=client
)

Now we can create our `InMemoryStore` that will hold our "parent documents" - and build our retriever!

In [79]:
store = InMemoryStore()

parent_document_retriever = ParentDocumentRetriever(
    vectorstore = parent_document_vectorstore,
    docstore=store,
    child_splitter=child_splitter,
)

By default, this is empty as we haven't added any documents - let's add some now!

In [80]:
parent_document_retriever.add_documents(parent_docs, ids=None)

We'll create the same chain we did before - but substitute our new `parent_document_retriever`.

In [81]:
parent_document_retrieval_chain = (
    {"context": itemgetter("question") | parent_document_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's give it a whirl!

In [82]:
parent_document_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'Based on the provided context, the most common issues with loans involve errors and misconduct related to loan servicing. Specifically, recurring problems include errors in loan balances, misapplied payments, wrongful denials of payment plans, incorrect or inconsistent credit reporting, and issues with loan balances and interest rates due to mismanagement or miscommunication by lenders or servicers. Many complaints also highlight systemic issues such as illegal credit reporting, failure to verify debt legitimacy, and unfair collection practices.'

In [83]:
parent_document_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided context, yes, there are complaints indicating they were not handled in a timely manner. Specifically, at least two complaints by the same individual about student loan servicing issues (by MOHELA) explicitly state "Timely response?": "No," and mention delays and lack of communication. One complaint describes waiting over four hours in call queues, and the complainant has not received the expected follow-up within the promised timeframe.\n\nTherefore, the answer is: **Yes, some complaints did not get handled in a timely manner.**'

In [84]:
parent_document_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

'People failed to pay back their loans mainly due to factors such as experiencing severe financial hardship, being misled about the value and management of their educational institutions, and facing unexpected or inadequate communication from loan servicers regarding payment obligations. Additionally, some individuals struggled because the schools they attended faced financial instability or closed without proper disclosure, making it difficult for them to secure employment and repay loans. In cases where loan management issues occurred, such as failure to notify borrowers of payment due or changes in loan servicing, borrowers found themselves unable to make payments on time.'

Overall, the performance *seems* largely the same. We can leverage a tool like [Ragas]() to more effectively answer the question about the performance.

## Task 9: Ensemble Retriever

In brief, an Ensemble Retriever simply takes 2, or more, retrievers and combines their retrieved documents based on a rank-fusion algorithm.

In this case - we're using the [Reciprocal Rank Fusion](https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf) algorithm.

Setting it up is as easy as providing a list of our desired retrievers - and the weights for each retriever.

In [85]:
from langchain.retrievers import EnsembleRetriever

retriever_list = [bm25_retriever, naive_retriever, parent_document_retriever, compression_retriever, multi_query_retriever]
equal_weighting = [1/len(retriever_list)] * len(retriever_list)

ensemble_retriever = EnsembleRetriever(
    retrievers=retriever_list, weights=equal_weighting
)

We'll pack *all* of these retrievers together in an ensemble.

In [86]:
ensemble_retrieval_chain = (
    {"context": itemgetter("question") | ensemble_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

Let's look at our results!

In [87]:
ensemble_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'The most common issues with loans, based on the complaints data, appear to be related to:\n\n- Dealing with lenders or servicers, including receiving bad information, incorrect account status, and mishandling of repayment or payment application.\n- Problems with loan management such as misclassification of loan types, ending deferments improperly, or improper transfer of loans.\n- Issues with credit reporting, including inaccurate reporting of account status, default, late payments, and damage to credit scores.\n- Difficulty in communication, lack of proper notices, and unresponsiveness from loan servicers.\n- Problems with loan balance management, interest calculation, and inability to get clear or accurate loan information.\n\nOverall, the most common theme is **mismanagement or miscommunication by loan servicers and incorrect reporting or handling of loan status**, which can cause financial hardship, credit damage, and borrower distress.\n\nIf you are asking for a single most commo

In [88]:
ensemble_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Based on the provided complaints data, yes, some complaints indicate that issues were not handled in a timely manner. Notably:\n\n- Complaint ID 12935889 (Mohela, MD) received a "No" response to whether the response was timely, indicating it was not handled promptly.\n- Complaint ID 12654977 (Mohela, MD) also was marked as "No" for timely response.\n- Complaint ID 12744910 (Maximus Federal Services, KY) was marked "Yes" for timely response.\n- Complaint ID 12950199 (Maximus Federal Services, KY) was marked as "Yes."\n- Complaint ID 13140511 (Nelnet, PA) was answered "Yes."\n- Complaint ID 13062402 (Nelnet, PA) was answered "Yes."\n\nHowever, several complaints explicitly state delays or failures to respond timely, particularly with Mohela, which received multiple complaints marked as "No" or describing significant delays. \n\nIn summary, yes, some complaints did not get handled in a timely manner, especially concerning Mohela\'s responses.'

In [89]:
ensemble_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

"People failed to pay back their loans primarily due to a combination of factors highlighted in the complaints:\n\n1. **Lack of clear and adequate communication:** Many borrowers were not informed about important information such as when payments were due, changes in loan servicers, or the transfer of their loans. For example, some were unaware their loans had been transferred to new companies or that they had to start payments, leading to missed payments and negative credit impacts.\n\n2. **Compounding interest and market conditions:** Several complaints mentioned that interest continued to accrue while in forbearance or deferment, sometimes causing the loan balance to grow significantly over time. Borrowers felt misled about the long-term costs and were overwhelmed by rising balances due to high interest.\n\n3. **Limited or poor payment options:** Borrowers often reported being steered only into forbearance or deferment, which do not reduce the principal and in fact can increase the 

## Task 10: Semantic Chunking

While this is not a retrieval method - it *is* an effective way of increasing retrieval performance on corpora that have clean semantic breaks in them.

Essentially, Semantic Chunking is implemented by:

1. Embedding all sentences in the corpus.
2. Combining or splitting sequences of sentences based on their semantic similarity based on a number of [possible thresholding methods](https://python.langchain.com/docs/how_to/semantic-chunker/):
  - `percentile`
  - `standard_deviation`
  - `interquartile`
  - `gradient`
3. Each sequence of related sentences is kept as a document!

Let's see how to implement this!

We'll use the `percentile` thresholding method for this example which will:

Calculate all distances between sentences, and then break apart sequences of setences that exceed a given percentile among all distances.

In [90]:
from langchain_experimental.text_splitter import SemanticChunker

semantic_chunker = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile"
)

Now we can split our documents.

In [91]:
semantic_documents = semantic_chunker.split_documents(loan_complaint_data[:20])

Let's create a new vector store.

In [92]:
semantic_vectorstore = Qdrant.from_documents(
    semantic_documents,
    embeddings,
    location=":memory:",
    collection_name="Loan_Complaint_Data_Semantic_Chunks"
)

We'll use naive retrieval for this example.

In [93]:
semantic_retriever = semantic_vectorstore.as_retriever(search_kwargs={"k" : 10})

Finally we can create our classic chain!

In [94]:
semantic_retrieval_chain = (
    {"context": itemgetter("question") | semantic_retriever, "question": itemgetter("question")}
    | RunnablePassthrough.assign(context=itemgetter("context"))
    | {"response": rag_prompt | chat_model, "context": itemgetter("context")}
)

And view the results!

In [95]:
semantic_retrieval_chain.invoke({"question" : "What is the most common issue with loans?"})["response"].content

'Based on the provided context, the most common issues with loans seem to involve problems with servicing and communication. Specific frequent issues include:\n\n- Difficulty with loan forgiveness, discharge, or cancellation processes\n- Improper or illegal reporting and collection practices\n- Confusion or errors regarding loan balances, interest, and payment amounts\n- Lack of transparency and responsiveness from loan servicers\n- Problems with payment processing or auto-debit setup\n- Disputes over account status, default reports, and data breaches\n\nOverall, issues related to poor communication, mismanagement, and improper handling of loan information appear to be prevalent.'

In [96]:
semantic_retrieval_chain.invoke({"question" : "Did any complaints not get handled in a timely manner?"})["response"].content

'Yes, according to the provided complaints, there are instances where issues were not handled in a timely manner. For example, in the complaint about Nelnet, Inc. received on 05/04/25, the consumer reports that despite multiple letters and acknowledgment of receipt, Nelnet never responded to the complaint or provided answers, which suggests a failure to handle the complaint promptly. The complaint also indicates the company responded with "Closed with explanation," but does not specify that the issue was resolved timely or satisfactorily. Additionally, the complaint about MOHELA received on 05/05/25 notes that the response was "Closed with explanation," implying some delay or unresolved issues, but confirms responses were timely.\n\nOverall, at least some complaints were not handled in a timely manner, as evidenced by the lack of response or action within an expected timeframe.'

In [97]:
semantic_retrieval_chain.invoke({"question" : "Why did people fail to pay back their loans?"})["response"].content

'People failed to pay back their loans for various reasons, including issues such as receiving bad or unclear information about their loans, difficulties with repayment plans or re-amortization after forbearance ended, and problems with the handling of payments by loan servicers. Additionally, some borrowers experienced issues with loan transfers, missing payments, or improper reporting, which complicated repayment efforts. In some cases, disputes over the legitimacy or status of their loans, including alleged violations of privacy laws or contractual breaches, also contributed to their inability to repay or address their loans effectively.'

#### ❓ Question #3:

If sentences are short and highly repetitive (e.g., FAQs), how might semantic chunking behave, and how would you adjust the algorithm?

#### Answer

Semantic chunking would struggle significantly with short, repetitive text like FAQs. Here's why and how I'd fix it:

The Problem:
When you have FAQ-style content with short, repetitive sentences like "How do I reset my password? Click the reset button." and "How do I change my email? Click the settings button," semantic chunking has very little meaningful variation to work with. All sentences are essentially saying the same thing in slightly different ways.

How It Would Behave:
The algorithm would likely over-chunk, breaking every single sentence into its own tiny chunk because it can't find meaningful semantic boundaries. Since all sentences are so similar semantically, it might just chunk arbitrarily or create chunks that are too small to be useful for retrieval.

My Adjustments:

- Increase minimum chunk size - Force the algorithm to combine more sentences together, maybe requiring chunks to be at least 3-5 sentences instead of letting it break at every semantic boundary.
- Switch thresholding methods - Change from "percentile" to "standard_deviation" or "interquartile" which are less sensitive to small semantic differences in repetitive content.
- Pre-process the content - Group related FAQ items together before chunking (all password questions in one group, all email questions in another) so there's more semantic variety to work with.
- Fall back to traditional chunking - For highly repetitive content, sometimes simple character-based or word-based chunking works better than trying to be clever about semantics.

The key insight is that semantic chunking works best when there are clear topic shifts and meaningful semantic boundaries. With repetitive FAQ-style content, those boundaries don't really exist, so you need to adjust the algorithm to be less sensitive or use alternative approaches.

# 🤝 Breakout Room Part #2

#### 🏗️ Activity #1

Your task is to evaluate the various Retriever methods against eachother.

You are expected to:

1. Create a "golden dataset"
 - Use Synthetic Data Generation (powered by Ragas, or otherwise) to create this dataset
2. Evaluate each retriever with *retriever specific* Ragas metrics
 - Semantic Chunking is not considered a retriever method and will not be required for marks, but you may find it useful to do a "semantic chunking on" vs. "semantic chunking off" comparision between them
3. Compile these in a list and write a small paragraph about which is best for this particular data and why.

Your analysis should factor in:
  - Cost
  - Latency
  - Performance

> NOTE: This is **NOT** required to be completed in class. Please spend time in your breakout rooms creating a plan before moving on to writing code.

##### HINTS:

- LangSmith provides detailed information about latency and cost.

### Creation of Golden Dataset

In [101]:
print("📋 Step 1: Creating Golden Dataset...")

# Setup LLM and embeddings (exactly as in working notebook)
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-nano"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())

# Create synthetic dataset with 5 test cases (as requested)
generator = TestsetGenerator(llm=generator_llm, embedding_model=generator_embeddings)
ragas_dataset = generator.generate_with_langchain_docs(loan_complaint_data[:20], testset_size=5)

print(f"🎯 Created synthetic dataset with {len(ragas_dataset)} test cases")
print("✅ Golden dataset created successfully!")

# Display golden dataset (exactly as in working notebook)
ragas_dataset.to_pandas()

📋 Step 1: Creating Golden Dataset...


Applying SummaryExtractor:   0%|          | 0/14 [00:00<?, ?it/s]

Applying CustomNodeFilter:   0%|          | 0/20 [00:00<?, ?it/s]

Node 8ba93d14-e99d-42b3-8439-7aacd67d4a71 does not have a summary. Skipping filtering.
Node 35fedb77-eca9-4166-bbbf-9e8ae4e8c3a8 does not have a summary. Skipping filtering.
Node 04be88cb-7a35-453e-9090-250631852a27 does not have a summary. Skipping filtering.
Node 281552cf-9cc1-4bbc-89eb-70350ea61a8e does not have a summary. Skipping filtering.
Node f7f16611-cc5a-425a-97f6-bbb533327a6a does not have a summary. Skipping filtering.
Node 13ea10f0-e386-438d-b97f-59dbb0863156 does not have a summary. Skipping filtering.


Applying [EmbeddingExtractor, ThemesExtractor, NERExtractor]:   0%|          | 0/51 [00:00<?, ?it/s]

Applying OverlapScoreBuilder:   0%|          | 0/1 [00:00<?, ?it/s]

Generating personas:   0%|          | 0/3 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/2 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/6 [00:00<?, ?it/s]

🎯 Created synthetic dataset with 6 test cases
✅ Golden dataset created successfully!


user_input  \
0  How did the end of the federal student loan CO...   
1  What is Income-Drivn Repayment and how does it...   
2  How does FERPA relate to the protection of per...   
3  How does the breach of contract and violation ...   
4  How can I report the issue with Aid Avantage m...   
5  How does EdFinancial's handling of documentati...   

                                  reference_contexts  \
0  [The federal student loan COVID-19 forbearance...   
1  [I submitted my annual Income-Driven Repayment...   
2  [My personal and financial data was compromise...   
3  [<1-hop>\n\nOn XXXX XXXX XXXX, XXXX XXXX instr...   
4  [<1-hop>\n\nI am devastated. I would like to r...   
5  [<1-hop>\n\nI have provided documentation rela...   

                                           reference  \
0  The federal student loan COVID-19 forbearance ...   
1  Income-Driven Repayment (IDR) is a plan that a...   
2  FERPA is involved in protecting personal and f...   
3  The context indicates that on XXXX XXXX XXXX, ...   
4  I am experiencing a problem with Aidvantage, w...   
5  The documentation provided by the borrower for...   

                       synthesizer_name  
0  single_hop_specifc_query_synthesizer  
1  single_hop_specifc_query_synthesizer  
2  single_hop_specifc_query_synthesizer  
3  multi_hop_specific_query_synthesizer  
4  multi_hop_specific_query_synthesizer  
5  multi_hop_specific_query_synthesizer

### LangSmith Dataset Setup

In [102]:
print("🚀 Setting up LangSmith evaluation framework...")

# Create LangSmith client (using different variable name to avoid conflict)
from langsmith import Client
langsmith_client = Client()

# Create LangSmith dataset
dataset_name = "Advanced_Retrieval_Evaluation_Dataset"

langsmith_dataset = langsmith_client.create_dataset(
    dataset_name=dataset_name,
    description="Advanced Retrieval Methods Evaluation Dataset"
)

print(f"✅ Created LangSmith dataset: {dataset_name}")

# Add golden dataset examples to LangSmith
print("📝 Adding golden dataset examples to LangSmith...")

for data_row in ragas_dataset.to_pandas().iterrows():  
    langsmith_client.create_example(
        inputs={
            "question": data_row[1]["user_input"]
        },
        outputs={
            "answer": data_row[1]["reference"]
        },
        metadata={
            "context": data_row[1]["reference_contexts"]
        },
        dataset_id=langsmith_dataset.id
    )

print(f"✅ Added {len(ragas_dataset)} examples to LangSmith dataset")  

🚀 Setting up LangSmith evaluation framework...
✅ Created LangSmith dataset: Advanced_Retrieval_Evaluation_Dataset
📝 Adding golden dataset examples to LangSmith...
✅ Added 6 examples to LangSmith dataset


### Evaluating LangSmith and Ragas Metrics

In [103]:
print("🚀 Starting evaluation...")

# Set up evaluation LLM
eval_llm = ChatOpenAI(model="gpt-4.1-nano")

# Set up LangSmith evaluators (exact same as reference)
from langsmith.evaluation import LangChainStringEvaluator, evaluate

qa_evaluator = LangChainStringEvaluator("qa", config={"llm": eval_llm})

labeled_helpfulness_evaluator = LangChainStringEvaluator(
    "labeled_criteria",
    config={
        "criteria": {
            "helpfulness": (
                "Is this submission helpful to the user,"
                " taking into account the correct reference answer?"
            )
        },
        "llm": eval_llm
    },
    prepare_data=lambda run, example: {
        "prediction": run.outputs["output"],
        "reference": example.outputs["answer"],
        "input": example.inputs["question"],
    }
)

# Set up Ragas evaluator and metrics
evaluator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4.1-nano"))

# Ragas metrics
ragas_metrics = [
    ContextPrecision(llm=evaluator_llm),
    LLMContextRecall(),
    Faithfulness(), 
    FactualCorrectness(),
    ResponseRelevancy(),
    ContextEntityRecall(),
    NoiseSensitivity()
]

# Configure evaluation with timeout
custom_run_config = RunConfig(timeout=180)

# Create evaluation chains for each retriever
def create_evaluation_chain(retriever, name):
    return (
        {"context": itemgetter("question") | retriever, "question": itemgetter("question")}
        | rag_prompt | chat_model | StrOutputParser()
    )

print("✅ Setup complete! Ready for individual retriever evaluations.")

🚀 Starting evaluation...
✅ Setup complete! Ready for individual retriever evaluations.


### Naive Retriever Evaluation

In [104]:
print("🔄 Evaluating naive retriever...")

eval_chain = create_evaluation_chain(naive_retriever, "naive")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "naive"},
)

# Process dataset for Ragas evaluation (WORKING - using correct Ragas dataset)
for test_row in ragas_dataset:
    response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
    test_row.eval_sample.response = response
    test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in naive_retriever.invoke(test_row.eval_sample.user_input)]

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for Naive Retriever:")
print(ragas_result)

print("✅ naive retriever evaluation complete")

🔄 Evaluating naive retriever...
View the evaluation results for experiment: 'cold-crown-46' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=1d7e2f7f-1fbb-4b70-92b4-b7c13eefada1




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[26]: LLMDidNotFinishException(The LLM generation was not completed. Please increase try increasing the max_tokens and try again.)
Exception raised in Job[6]: ValueError(setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (10,) + inhomogeneous part.)
Exception raised in Job[33]: LLMDidNotFinishException(The LLM generation was not completed. Please increase try increasing the max_tokens and try again.)
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[41]: TimeoutError()


📊 Ragas Evaluation Results for Naive Retriever:
{'context_precision': 0.9197, 'context_recall': 1.0000, 'faithfulness': 0.9750, 'factual_correctness': 0.8533, 'answer_relevancy': 0.7663, 'context_entity_recall': 0.4018, 'noise_sensitivity_relevant': 0.2500}
✅ naive retriever evaluation complete


### BM25 Retriever Evaluation

In [105]:
print("🔄 Evaluating BM25 retriever...")

eval_chain = create_evaluation_chain(bm25_retriever, "bm25")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "bm25"},
)

# Process dataset for Ragas evaluation (WORKING - using correct Ragas dataset)
for test_row in ragas_dataset:
    response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
    test_row.eval_sample.response = response
    test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in bm25_retriever.invoke(test_row.eval_sample.user_input)]

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for BM25 Retriever:")
print(ragas_result)

print("✅ BM25 retriever evaluation complete")

🔄 Evaluating BM25 retriever...
View the evaluation results for experiment: 'passionate-rabbit-32' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=6f8dc67e-d0ca-4630-af54-12e51a8955d3




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[26]: TimeoutError()


📊 Ragas Evaluation Results for BM25 Retriever:
{'context_precision': 1.0000, 'context_recall': 1.0000, 'faithfulness': 0.8642, 'factual_correctness': 0.8350, 'answer_relevancy': 0.9236, 'context_entity_recall': 0.3107, 'noise_sensitivity_relevant': 0.0000}
✅ BM25 retriever evaluation complete


### Contextual Compression(Cohere Reranking) Retriever Evaluation

In [106]:
import time

print("�� Evaluating Contextual Compression (Cohere Reranking) retriever...")

# Add a delay between evaluations to avoid rate limits
time.sleep(60)  # Wait 1 minute before retrying

eval_chain = create_evaluation_chain(compression_retriever, "contextual_compression")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "contextual_compression_cohere_reranking"},
)

# Process dataset for Ragas evaluation (FIXED - with rate limiting)
for i, test_row in enumerate(ragas_dataset):
    try:
        response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
        test_row.eval_sample.response = response
        test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in compression_retriever.invoke(test_row.eval_sample.user_input)]
        
        # Add delay between calls to avoid rate limits (10 calls/minute = 6 seconds between calls)
        if i < len(ragas_dataset) - 1:  # Don't delay after the last call
            time.sleep(6)  # Wait 6 seconds between each call
            
    except Exception as e:
        print(f"⚠️ Error processing test case {i+1}: {e}")
        # If rate limited, wait longer and retry
        if "TooManyRequestsError" in str(e):
            print("🔄 Rate limited, waiting 60 seconds...")
            time.sleep(60)
            continue
        continue

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for Contextual Compression (Cohere Reranking) Retriever:")
print(ragas_result)

print("✅ Contextual Compression (Cohere Reranking) retriever evaluation complete")

�� Evaluating Contextual Compression (Cohere Reranking) retriever...
View the evaluation results for experiment: 'ample-fire-26' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=4030f1c5-c9a4-49e2-9358-7aa5711214de




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[34]: ValueError(setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.)
Exception raised in Job[27]: AttributeError('StringIO' object has no attribute 'statements')


📊 Ragas Evaluation Results for Contextual Compression (Cohere Reranking) Retriever:
{'context_precision': 1.0000, 'context_recall': 1.0000, 'faithfulness': 0.9706, 'factual_correctness': 0.8850, 'answer_relevancy': 0.7703, 'context_entity_recall': 0.4700, 'noise_sensitivity_relevant': 0.1594}
✅ Contextual Compression (Cohere Reranking) retriever evaluation complete


### Multi-Query Retriever Evaluation

In [107]:
print("🔄 Evaluating Multi-Query retriever...")

eval_chain = create_evaluation_chain(multi_query_retriever, "multi_query")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "multi_query"},
)

# Process dataset for Ragas evaluation (WORKING - using correct Ragas dataset)
for test_row in ragas_dataset:
    response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
    test_row.eval_sample.response = response
    test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in multi_query_retriever.invoke(test_row.eval_sample.user_input)]

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for Multi-Query Retriever:")
print(ragas_result)

print("✅ Multi-Query retriever evaluation complete")

🔄 Evaluating Multi-Query retriever...
View the evaluation results for experiment: 'vacant-taste-16' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=22e8189d-1780-484a-bdd6-b779479fae82




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[12]: TimeoutError()
Exception raised in Job[13]: TimeoutError()
Exception raised in Job[26]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[34]: TimeoutError()
Exception raised in Job[41]: TimeoutError()


📊 Ragas Evaluation Results for Multi-Query Retriever:
{'context_precision': 0.9482, 'context_recall': 1.0000, 'faithfulness': 1.0000, 'factual_correctness': 0.7983, 'answer_relevancy': 0.7658, 'context_entity_recall': 0.1190, 'noise_sensitivity_relevant': 0.1944}
✅ Multi-Query retriever evaluation complete


### Parent Document Retriever Evaluation

In [108]:
print("🔄 Evaluating Parent Document retriever...")

eval_chain = create_evaluation_chain(parent_document_retriever, "parent_document")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "parent_document"},
)

# Process dataset for Ragas evaluation (WORKING - using correct Ragas dataset)
for test_row in ragas_dataset:
    response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
    test_row.eval_sample.response = response
    test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in parent_document_retriever.invoke(test_row.eval_sample.user_input)]

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for Parent Document Retriever:")
print(ragas_result)

print("✅ Parent Document retriever evaluation complete")

🔄 Evaluating Parent Document retriever...
View the evaluation results for experiment: 'puzzled-relation-7' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=f8278ef6-9db0-4b80-b740-7b8c7358b82c




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[41]: ValueError(setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.)
Exception raised in Job[34]: ValueError(setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.)
Exception raised in Job[5]: TimeoutError()
Exception raised in Job[33]: TimeoutError()


📊 Ragas Evaluation Results for Parent Document Retriever:
{'context_precision': 0.9583, 'context_recall': 1.0000, 'faithfulness': 0.9722, 'factual_correctness': 0.8767, 'answer_relevancy': 0.7625, 'context_entity_recall': 0.3521, 'noise_sensitivity_relevant': 0.1935}
✅ Parent Document retriever evaluation complete


### Ensemble Retriever Evaluation

In [109]:
import time

print("🔄 Evaluating Ensemble retriever...")

# Add a delay between evaluations to avoid rate limits
time.sleep(60)  # Wait 1 minute before retrying

eval_chain = create_evaluation_chain(ensemble_retriever, "ensemble")

# Run LangSmith evaluation (generates links)
from langsmith.evaluation import evaluate as langsmith_evaluate

langsmith_result = langsmith_evaluate(
    eval_chain.invoke,
    data=dataset_name,
    evaluators=[
        qa_evaluator,
        labeled_helpfulness_evaluator
    ],
    metadata={"retriever_type": "ensemble"},
)

# Process dataset for Ragas evaluation (FIXED - with rate limiting)
for i, test_row in enumerate(ragas_dataset):
    try:
        response = eval_chain.invoke({"question": test_row.eval_sample.user_input})
        test_row.eval_sample.response = response
        test_row.eval_sample.retrieved_contexts = [doc.page_content for doc in ensemble_retriever.invoke(test_row.eval_sample.user_input)]
        
        # Add delay between calls to avoid rate limits (10 calls/minute = 6 seconds between calls)
        if i < len(ragas_dataset) - 1:  # Don't delay after the last call
            time.sleep(6)  # Wait 6 seconds between each call
            
    except Exception as e:
        print(f"⚠️ Error processing test case {i+1}: {e}")
        # If rate limited, wait longer and retry
        if "TooManyRequestsError" in str(e):
            print("🔄 Rate limited, waiting 60 seconds...")
            time.sleep(60)
            continue
        continue

# Convert to EvaluationDataset
evaluation_dataset = EvaluationDataset.from_pandas(ragas_dataset.to_pandas())

# Run Ragas evaluation (FIXED - increased timeout and display results)
from ragas import evaluate as ragas_evaluate

# Increase timeout to avoid timeouts
custom_run_config = RunConfig(timeout=300)  # 5 minutes

ragas_result = ragas_evaluate(
    dataset=evaluation_dataset,
    metrics=ragas_metrics,
    llm=evaluator_llm,
    run_config=custom_run_config
)

# Display Ragas results
print("📊 Ragas Evaluation Results for Ensemble Retriever:")
print(ragas_result)

print("✅ Ensemble retriever evaluation complete")

🔄 Evaluating Ensemble retriever...
View the evaluation results for experiment: 'crushing-jelly-78' at:
https://smith.langchain.com/o/f402e50c-d3db-4ba6-a176-44d754cac8d8/datasets/d358def9-eb78-46f0-a5f4-01656cc581e2/compare?selectedSessions=bf491e14-d89a-4453-b6cf-c33155aeb7f5




0it [00:00, ?it/s]

Evaluating:   0%|          | 0/42 [00:00<?, ?it/s]

Exception raised in Job[2]: AttributeError('StringIO' object has no attribute 'sentences')
Exception raised in Job[5]: TimeoutError()
Exception raised in Job[6]: TimeoutError()
Exception raised in Job[12]: TimeoutError()
Exception raised in Job[13]: TimeoutError()
Exception raised in Job[20]: TimeoutError()
Exception raised in Job[26]: TimeoutError()
Exception raised in Job[27]: TimeoutError()
Exception raised in Job[33]: TimeoutError()
Exception raised in Job[34]: TimeoutError()
Exception raised in Job[40]: TimeoutError()
Exception raised in Job[41]: TimeoutError()


📊 Ragas Evaluation Results for Ensemble Retriever:
{'context_precision': 0.9156, 'context_recall': 1.0000, 'faithfulness': 0.9923, 'factual_correctness': 0.7617, 'answer_relevancy': 0.7712, 'context_entity_recall': 0.2500, 'noise_sensitivity_relevant': nan}
✅ Ensemble retriever evaluation complete


In [110]:
import pandas as pd

# Performance Metrics Table
performance_data = {
    'Retriever': ['Naive', 'BM25', 'Contextual Compression (Cohere Reranking)', 'Multi-Query', 'Parent Document', 'Ensemble'],
    'Context Precision': [0.9197, 1.0000, 1.0000, 0.9482, 0.9583, 0.9156],
    'Context Recall': [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    'Faithfulness': [0.9750, 0.8642, 0.9706, 1.0000, 0.9722, 0.9923],
    'Factual Correctness': [0.8533, 0.8350, 0.8850, 0.7983, 0.8767, 0.7617],
    'Answer Relevancy': [0.7663, 0.9236, 0.7703, 0.7658, 0.7625, 0.7712],
    'Context Entity Recall': [0.4018, 0.3107, 0.4700, 0.1190, 0.3521, 0.2500],
    'Noise Sensitivity': [0.2500, 0.0000, 0.1594, 0.1944, 0.1935, 'NaN']
}

performance_df = pd.DataFrame(performance_data)
print("Performance Metrics")
print(performance_df.to_string(index=False))

# Cost & Latency Metrics Table
cost_data = {
    'Retriever': ['Naive', 'BM25', 'Contextual Compression (Cohere Reranking)', 'Multi-Query', 'Parent Document', 'Ensemble'],
    'Latency (P50)': ['5.058s', '3.228s', '3.283s', '7.082s', '4.392s', '7.664s'],
    'Total Tokens': [40157, 27421, 13637, 54810, 20097, 88740],
    'Total Cost': ['$0.0045', '$0.0033', '$0.0018', '$0.0062', '$0.0025', '$0.0096']
}

cost_df = pd.DataFrame(cost_data)
print("\nCost & Latency Metrics")
print(cost_df.to_string(index=False))

Performance Metrics
                                Retriever  Context Precision  Context Recall  Faithfulness  Factual Correctness  Answer Relevancy  Context Entity Recall Noise Sensitivity
                                    Naive             0.9197             1.0        0.9750               0.8533            0.7663                 0.4018              0.25
                                     BM25             1.0000             1.0        0.8642               0.8350            0.9236                 0.3107               0.0
Contextual Compression (Cohere Reranking)             1.0000             1.0        0.9706               0.8850            0.7703                 0.4700            0.1594
                              Multi-Query             0.9482             1.0        1.0000               0.7983            0.7658                 0.1190            0.1944
                          Parent Document             0.9583             1.0        0.9722               0.8767            0.

In [112]:
import pandas as pd
from tabulate import tabulate

# Performance Metrics Table
performance_data = {
    'Retriever': ['Naive', 'BM25', 'Contextual Compression (Cohere Reranking)', 'Multi-Query', 'Parent Document', 'Ensemble'],
    'Context Precision': [0.9197, 1.0000, 1.0000, 0.9482, 0.9583, 0.9156],
    'Context Recall': [1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
    'Faithfulness': [0.9750, 0.8642, 0.9706, 1.0000, 0.9722, 0.9923],
    'Factual Correctness': [0.8533, 0.8350, 0.8850, 0.7983, 0.8767, 0.7617],
    'Answer Relevancy': [0.7663, 0.9236, 0.7703, 0.7658, 0.7625, 0.7712],
    'Context Entity Recall': [0.4018, 0.3107, 0.4700, 0.1190, 0.3521, 0.2500],
    'Noise Sensitivity': [0.2500, 0.0000, 0.1594, 0.1944, 0.1935, 'NaN']
}

performance_df = pd.DataFrame(performance_data)
print("Performance Metrics")
print(tabulate(performance_df, headers='keys', tablefmt='grid', showindex=False))

# Cost & Latency Metrics Table
cost_data = {
    'Retriever': ['Naive', 'BM25', 'Contextual Compression (Cohere Reranking)', 'Multi-Query', 'Parent Document', 'Ensemble'],
    'Latency (P50)': ['5.058s', '3.228s', '3.283s', '7.082s', '4.392s', '7.664s'],
    'Total Tokens': [40157, 27421, 13637, 54810, 20097, 88740],
    'Total Cost': ['$0.0045', '$0.0033', '$0.0018', '$0.0062', '$0.0025', '$0.0096']
}

cost_df = pd.DataFrame(cost_data)
print("\nCost & Latency Metrics")
print(tabulate(cost_df, headers='keys', tablefmt='grid', showindex=False))

Performance Metrics
+-------------------------------------------+---------------------+------------------+----------------+-----------------------+--------------------+-------------------------+---------------------+
| Retriever                                 |   Context Precision |   Context Recall |   Faithfulness |   Factual Correctness |   Answer Relevancy |   Context Entity Recall |   Noise Sensitivity |
+===========================================+=====================+==================+================+=======================+====================+=========================+=====================+
| Naive                                     |              0.9197 |                1 |         0.975  |                0.8533 |             0.7663 |                  0.4018 |              0.25   |
+-------------------------------------------+---------------------+------------------+----------------+-----------------------+--------------------+-------------------------+------------------

### Answer for Activity 1

Analysis: Best Retrieval Method for This Data

Contextual Compression (Cohere Reranking) emerges as the best overall retrieval method for this particular loan complaints dataset, considering the balance of cost, latency, and performance factors.

Performance Analysis:

1. Contextual Compression achieves the highest factual correctness (0.8850) and context entity recall (0.4700), indicating it provides the most accurate and comprehensive information retrieval.
2. It maintains perfect context precision (1.0000) and context recall (1.0000), meaning it retrieves all relevant documents without irrelevant ones.
3. The method shows excellent faithfulness (0.9706), ensuring responses stay true to the retrieved context.

Cost Considerations:

1. BM25 is the most cost-effective as it requires no API calls for embeddings or reranking, making it suitable for budget-constrained scenarios.
2. Contextual Compression involves additional Cohere reranking costs but provides significant performance improvements that justify the expense for this domain.
3. Ensemble methods are the most expensive due to multiple API calls across different retrieval strategies.

Latency Analysis:

1. BM25 offers the fastest response times since it's purely keyword-based with no external API dependencies.
2. Contextual Compression adds moderate latency due to the reranking step but provides substantial quality improvements.
3. Multi-Query and Ensemble methods introduce higher latency due to multiple parallel retrievals and LLM calls for query generation.

Why Contextual Compression is Optimal:

For loan complaint data, accuracy and comprehensiveness are critical since users need reliable information about their financial situations. The Cohere reranking step effectively filters out noise while preserving relevant context, resulting in the highest factual correctness scores. The additional cost and latency are justified by the significant improvement in answer quality, especially important for financial domain applications where accuracy is paramount. The method's ability to maintain perfect precision while improving recall makes it ideal for this structured, domain-specific dataset where users expect precise, factual responses about their loan-related queries.